export const sectionColorsMap = {
  section_variant_1: {
    backgroundColor: '#ffffff',
    textColor: '#1a1a1a',
    accentColor: '#ff6600',
    linkColor: '#0056b3',
    textDecoration: 'underline',
    textDecorationColor: '#0056b3',
    linkHoverColor: '#003366',
    linkHoverTextDecoration: 'underline',
    linkHoverTextDecorationColor: '#003366',
    blockquoteTextColor: '#333333',
    blockquoteBackgroundColor: '#f9f9f9',
    blockquoteAccentColor: '#ffcc00',
  },
  section_variant_2: {
    backgroundColor: '#f0f0f0',
    textColor: '#333333',
    accentColor: '#00cc99',
    linkColor: '#007bff',
    textDecoration: 'underline',
    textDecorationColor: '#007bff',
    linkHoverColor: '#0056b3',
    linkHoverTextDecoration: 'underline',
    linkHoverTextDecorationColor: '#0056b3',
    blockquoteTextColor: '#444444',
    blockquoteBackgroundColor: '#eeeeee',
    blockquoteAccentColor: '#66ccff',
  },
  section_variant_3: {
    backgroundColor: '#e6f2ff',
    textColor: '#222222',
    accentColor: '#0099ff',
    linkColor: '#004085',
    textDecoration: 'underline',
    textDecorationColor: '#004085',
    linkHoverColor: '#002752',
    linkHoverTextDecoration: 'underline',
    linkHoverTextDecorationColor: '#002752',
    blockquoteTextColor: '#555555',
    blockquoteBackgroundColor: '#d9eaf7',
    blockquoteAccentColor: '#3399ff',
  },
  section_variant_4: {
    backgroundColor: '#1a1a1a',
    textColor: '#f2f2f2',
    accentColor: '#ffcc00',
    linkColor: '#ff9900',
    textDecoration: 'underline',
    textDecorationColor: '#ff9900',
    linkHoverColor: '#cc7a00',
    linkHoverTextDecoration: 'underline',
    linkHoverTextDecorationColor: '#cc7a00',
    blockquoteTextColor: '#cccccc',
    blockquoteBackgroundColor: '#333333',
    blockquoteAccentColor: '#ffaa00',
  },
};
